name: Sync ys from algorithm-study to Daily_Leetcode_Study

on:
  push:
    branches:
      - main # algorithm-study의 main 브랜치가 변경될 때 실행
jobs:
  sync-folder:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout algorithm-study
        uses: actions/checkout@v4
        with:
          repository: yeahsdev/algorithm-study
          ref: main
          token: ${{ secrets.GH_PAT }} # 개인 액세스 토큰 필요

      - name: Copy ys to Daily_Leetcode_Study
        run: |
          mkdir Daily_Leetcode_Study
          cd Daily_Leetcode_Study
          git init
          git remote add origin https://github.com/yeahsdev/Daily_Leetcode_Study.git
          git fetch origin main
          git checkout -b main origin/main

          # algorithm-study의 특정 폴더 복사
          cd ..
          rsync -av --delete path/to/folder/in/algorithm-study/ Daily_Leetcode_Study/ys/

          cd Daily_Leetcode_Study
          git add .
          git commit -m "Sync specific folder from Repo1" || echo "No changes to commit"
          git push origin main

    env:
      GIT_AUTHOR_NAME: yeahsdev
      GIT_AUTHOR_EMAIL: yeahsdev@github.com
      GIT_COMMITTER_NAME: yeahsdev
      GIT_COMMITTER_EMAIL: yeahsdev@github.com
