name: Sync Folder to Repo B

on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때 실행

jobs:
  sync_folder:
    runs-on: ubuntu-latest
    steps:
      - name: Repo A 코드 가져오기
        uses: actions/checkout@v3

      - name: Git 설정 (사용자 정보 등록)
        run: |
          git config --global user.email "iyeahs71@gmail.com"
          git config --global user.name "yeahsdev"

      - name: Repo B 클론
        run: |
          git clone https://$GH_PAT@github.com/DailyLeetcodeStudy/Daily_Leetcode_Study.git Daily_Leetcode_Study
          cd Daily_Leetcode_Study
          git checkout main || git checkout -b main

      - name: 특정 폴더 동기화
        run: |
          rsync -av --delete Daily_Leetcode_Study/ Daily_Leetcode_Study/ys/

      - name: Repo B에 변경 사항 커밋 및 푸시
        run: |
          cd Daily_Leetcode_Study
          git add .
          git commit -m "Sync Daily_Leetcode_Study to ys" || echo "No changes to commit"
          git push origin main
