name: "Sync LeetHub (algorithm-study) to Daily_Leetcode_Study/ys"

on:
  push:
    branches:
      - main  # LeetHub가 algorithm-study의 main 브랜치에 푸시할 때 실행
  workflow_dispatch:  # 수동 실행 가능

jobs:
  sync-folder:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout algorithm-study (LeetHub repo)
        uses: actions/checkout@v4
        with:
          repository: yeahsdev/algorithm-study
          ref: main
          token: ${{ secrets.GH_PAT }}

      - name: Clone Daily_Leetcode_Study repository
        run: |
          git clone https://github.com/yeahsdev/Daily_Leetcode_Study.git repo2
          cd repo2
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git checkout main || git checkout -b main
          cd ..

      - name: Sync algorithm-study to ys folder in Daily_Leetcode_Study
        run: |
          rsync -av --delete . repo2/ys/  # ✅ algorithm-study 전체 내용을 Daily_Leetcode_Study/ys/에 동기화

          cd repo2
          git add .
          TODAY=$(date "+%Y-%m-%d")  # 오늘 날짜 가져오기
          git commit -m "Sync from algorithm-study to ys - $TODAY" || echo "No changes to commit"
          git push https://yeahsdev:${{ secrets.GH_PAT }}@github.com/yeahsdev/Daily_Leetcode_Study.git main

    env:
      GIT_AUTHOR_NAME: "GitHub Actions"
      GIT_AUTHOR_EMAIL: "actions@github.com"
      GIT_COMMITTER_NAME: "GitHub Actions"
      GIT_COMMITTER_EMAIL: "actions@github.com"
